import mehmetImg from "./fifa/mehmettuncay.png";
import doganerImg from "./fifa/doganerkose.png";
import alimertImg from "./fifa/alimertdogan.png";
import aytuncImg from "./fifa/aytunccakir.png";
import batuhanImg from "./fifa/batuhanozbay.png";
import berkImg from "./fifa/berkkarakus.png";
import burakImg from "./fifa/burakganidincer.png";
import denizImg from "./fifa/denizeren.png";
import enesImg from "./fifa/enesgirgin.png";
import erberkImg from "./fifa/erberkcoskun.png";
import hakanImg from "./fifa/hakanyildirim.png";
import ismailImg from "./fifa/ismailyamac.png";
import nevzatImg from "./fifa/nevzatkilic.png";
import orkunImg from "./fifa/orkunkutlu.png";
import sametImg from "./fifa/sametaktan.png";
import emreImg from "./fifa/taciemresen.png";
import yigitImg from "./fifa/yigitduman.png";
import edipImg from "./fifa/edipahmet.png";
import canerImg from "./fifa/canercaglayan.png";

export const players = [
  {
    id: 1,
    firstName: "Mehmet Tuncay",
    lastName: "Alkoç",
    position: "Kaleci",
    birthdate: 2005,
    shirtNum: 65,
    game: 5,
    goal: 0,
    assist: 0,
    redCard: 1,
    yellowCard: 0,
    photo: mehmetImg,
    insta: "https://www.instagram.com/meehmettuncay",
    desc: "Hızlı refleksleri ve soğukkanlılığıyla tanınan genç bir kaleci olan Mehmet, 2022'den bu yana Komodor FC'nin kalesini başarıyla korumaktadır.",
  },
  {
    id: 2,
    firstName: "Doğaner",
    lastName: "Köse",
    position: "Defans",
    birthdate: 2000,
    shirtNum: 2,
    game: 4,
    goal: 1,
    assist: 1,
    redCard: 2,
    yellowCard: 1,
    photo: doganerImg,
    insta: "https://www.instagram.com/dgnrkose",
    desc: "Topla oynamayı çok seven ve rakiplerinin önünde sürekli hareketli olan bir sağ bek olan Doğaner, Komodor FC'nin sağ kanadında enerjisi ve agresifliğiyle dikkat çekmektedir.",
  },
  {
    id: 3,
    firstName: "Mehmet Nevzat",
    lastName: "Kılıç",
    position: "Defans",
    birthdate: 2000,
    shirtNum: 4,
    game: 3,
    goal: 3,
    assist: 0,
    redCard: 1,
    yellowCard: 1,
    photo: nevzatImg,
    insta: "https://www.instagram.com/nevzatkilicc",
    desc: "Tandemdeki sağlam duruşu ve hava toplarındaki üstünlüğüyle tanınan Nevzat, Komodor FC savunmasının en güvenilir isimlerinden biridir.",
  },
  {
    id: 4,
    firstName: "Batuhan",
    lastName: "Özbay",
    position: "Defans",
    birthdate: 1998,
    shirtNum: 17,
    game: 4,
    goal: 1,
    assist: 1,
    redCard: 0,
    yellowCard: 2,
    photo: batuhanImg,
    insta: "https://www.instagram.com/bthnzby",
    desc: "Agresif ve kararlı oyun tarzıyla bilinen etkili bir savunmacı olan Özbay, Komodor FC'nin savunma hattında rakipleri durdurma konusundaki yeteneğiyle dikkat çekmektedir",
  },
  {
    id: 5,
    firstName: "Orkun",
    lastName: "Kutlu",
    position: "Defans",
    birthdate: 1999,
    shirtNum: 6,
    game: 0,
    goal: 0,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: orkunImg,
    insta: "https://www.instagram.com/orkunkutluu",
    desc: "Sağlam fiziği ve oyundaki akıllı müdahaleleriyle tanınan etkili bir stoper olan Orkun, Komodor FC savunmasının güvenilir bir direği olarak uzun süredir takımın temel taşlarından biridir.",
  },
  {
    id: 6,
    firstName: "Erberk",
    lastName: "Coşkun",
    position: "Defans",
    birthdate: 2000,
    shirtNum: 5,
    game: 2,
    goal: 2,
    assist: 1,
    redCard: 0,
    yellowCard: 0,
    photo: erberkImg,
    insta: "https://www.instagram.com/_erberkcoskun",
    desc: "Fiziksel gücü ve çok yönlülüğüyle tanınan Erberk, asıl mevkisi sağ bek olmasına rağmen, her pozisyonda etkili bir performans sergileyebilir. Komodor FC'nin her alanında oyun gücünü ve dinamik yapısını takımın başarısına katkı sağlamak için kullanmaktadır. ",
  },
  {
    id: 7,
    firstName: "Berk Ergül",
    lastName: "Karakuş",
    position: "Defans",
    birthdate: 2000,
    shirtNum: 8,
    game: 1,
    goal: 0,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: berkImg,
    insta: "https://www.instagram.com/berk__karakus",
    desc: "Forma şansı bulduğunda mükemmel bir performans sergileyen stoperimiz Berk, her fırsatı iyi değerlendirmesiyle takımına önemli katkılar sağlıyor ve savunmadaki güvenilirliğini her maçta ortaya koyuyor.",
  },
  {
    id: 8,
    firstName: "Deniz",
    lastName: "Eren",
    position: "Defans",
    birthdate: 1999,
    shirtNum: 27,
    game: 2,
    goal: 1,
    assist: 2,
    redCard: 1,
    yellowCard: 0,
    photo: denizImg,
    insta: "https://www.instagram.com/_denizerenn",
    desc: "Yüksek enerjisi ve etkili savunma becerileriyle tanınan sağ bek oyuncumuz Deniz Eren, takımın sağ kanadında sürekli bir tehdit oluşturarak rakiplerinin başını sürekli belaya sokuyor. Hızlı ve kararlı oyun tarzı, Komodor FC'nin savunmasını güçlendiren önemli bir unsur.",
  },
  {
    id: 9,
    firstName: "Burak Gani",
    lastName: "Dinçer",
    position: "Defans",
    birthdate: 1997,
    shirtNum: 11,
    game: 3,
    goal: 1,
    assist: 3,
    redCard: 1,
    yellowCard: 0,
    photo: burakImg,
    insta: "https://www.instagram.com/burakganidincer",
    desc: "Top hakimiyeti ve skora katkısıyla dikkat çeken solbek oyuncumuz Gani, hem savunmada hem de hücumda etkili oyunuyla takımın önemli bir parçası haline gelmiştir. Teknik becerileri ve oyunu yönlendirme yeteneği sayesinde, Komodor FC'nin sol kanadında büyük bir güç oluşturmaktadır.",
  },
  {
    id: 10,
    firstName: "Abdulsamet",
    lastName: "Aktan",
    position: "Defans",
    birthdate: 2000,
    shirtNum: 69,
    game: 0,
    goal: 0,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: sametImg,
    insta: "https://www.instagram.com/sameetaktaan",
    desc: "Yaratıcı hücum yetenekleri ve etkili top sürme becerisiyle tanınan sol bek oyuncumuz Samet, özellikle ofansif pozisyonlarda büyük bir tehdit oluşturuyor. Sık sık rakip kaleye yönelik etkili koşular yaparak skora katkıda bulunuyor ve Komodor FC'nin hücum gücünü artırıyor.",
  },
  {
    id: 11,
    firstName: "İsmail Arda",
    lastName: "Yamaç",
    position: "Defans",
    birthdate: 2001,
    shirtNum: 19,
    game: 4,
    goal: 2,
    assist: 4,
    redCard: 0,
    yellowCard: 0,
    photo: ismailImg,
    insta: "https://www.instagram.com/ardayamac_",
    desc: "Defansif yetenekleri ve uluslararası tecrübesiyle tanınan milli oyuncumuz İsmail Arda, hem savunma hattında hem de takımın genel oyun düzeninde büyük bir rol oynuyor. Sağlam duruşu ve liderlik özellikleriyle, Komodor FC'nin savunmasını güçlendirirken, milli takımdaki deneyimiyle de takımımıza değerli bir katkı sağlıyor.",
  },
  {
    id: 12,
    firstName: "Ahmet Hakan",
    lastName: "Yıldırım",
    position: "Ortasaha",
    birthdate: 1999,
    shirtNum: 61.5,
    game: 4,
    goal: 8,
    assist: 4,
    redCard: 0,
    yellowCard: 1,
    photo: hakanImg,
    insta: "https://www.instagram.com/hakanylld",
    desc: "Takımın beyni olarak bilinen orta saha oyuncumuz Hakan, üstün top hakimiyeti ve oyun görüşüyle öne çıkıyor. Rakip savunmaları etkili bir şekilde dağıtarak, Komodor FC'nin hücumlarını yönlendiriyor ve oyunun temposunu kontrol ediyor. Stratejik pasları ve yaratıcı oyun anlayışıyla, takımın oyun düzeninin merkezinde bulunuyor.",
  },
  {
    id: 13,
    firstName: "Edip Ahmet",
    lastName: "Çapaoğlu",
    position: "Ortasaha",
    birthdate: 2001,
    shirtNum: 14,
    game: 2,
    goal: 1,
    assist: 1,
    redCard: 0,
    yellowCard: 0,
    photo: edipImg,
    insta: "https://www.instagram.com/edippahmet",
    desc: "Takıma yeni katılan yetenekli orta saha oyuncumuz Edip Ahmet, birebirdeki etkili performansı ve yaratıcı oyun tarzıyla dikkat çekiyor. Transferi büyük bir heyecan yarattı ve performansı merakla bekleniyor. Edip Ahmet'in teknik becerileri ve oyun zekası, Komodor FC'nin orta sahasını güçlendirecek ve sahada büyük bir etki yaratacak.",
  },
  {
    id: 14,
    firstName: "Ali Mert",
    lastName: "Doğan",
    position: "Ortasaha",
    birthdate: 1995,
    shirtNum: 33,
    game: 0,
    goal: 0,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: alimertImg,
    insta: "https://www.instagram.com/alimmertdogan",
    desc: "Son üç sezonun gol kralı olan yıldız oyuncumuz Ali Mert, olağanüstü bitiriciliği ve pozisyon bilgisiyle rakip kalecilerin kabusu haline geldi. Sürekli golleriyle takımımıza büyük katkı sağlayarak, Komodor FC'nin hücum gücünü en üst seviyeye taşıyor ve sahada attığı her golle rakiplerin psikolojisini bozuyor",
  },
  {
    id: 15,
    firstName: "Er Yiğit",
    lastName: "Duman",
    position: "Ortasaha",
    birthdate: 1998,
    shirtNum: 10,
    game: 4,
    goal: 3,
    assist: 5,
    redCard: 0,
    yellowCard: 0,
    photo: yigitImg,
    insta: "https://www.instagram.com/ygtdmn10",
    desc: "Takım kaptanımız Yiğit, liderlik özellikleri ve saha içindeki kararlılığıyla Komodor FC'nin vazgeçilmez bir parçasıdır. Oyunculara olan motivasyonu, takımın başarılarına büyük katkı sağlıyor. Yiğit'in liderliği, takımın uyumunu ve mücadele gücünü her maçta artırıyor.",
  },
  {
    id: 16,
    firstName: "Caner",
    lastName: "Çağlayan",
    position: "Ortasaha",
    birthdate: 1992,
    shirtNum: 26,
    game: 2,
    goal: 2,
    assist: 2,
    redCard: 0,
    yellowCard: 1,
    photo: canerImg,
    insta: "https://www.instagram.com/caglayancaner",
    desc: "Takımın en tecrübeli oyuncusu olan Caner Çağlayan, yalnızca yaşının getirdiği olgunlukla değil, aynı zamanda takım içinde kazandığı büyük saygıyla da dikkat çekiyor. Saha içinde ve dışında liderlik vasıflarını sergileyen Caner, futbol yetenekleriyle takım arkadaşlarını etkiliyor. Onun oyuna kattığı sakinlik, tecrübe ve becerisi, Komodor FC'nin en kritik anlarında takımın en güvendiği isimlerden biri olmasını sağlıyor.",
  },
  {
    id: 17,
    firstName: "Enes",
    lastName: "Girgin",
    position: "Forvet",
    birthdate: 1999,
    shirtNum: 20,
    game: 3,
    goal: 2,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: enesImg,
    insta: "https://www.instagram.com/enesgirgin28",
    desc: "Takımın nöbetçi golcüsü olan Enes, sahaya çıktığında büyük bir etki yaratarak maçların kaderini değiştirebiliyor. Oyuna girdiğinde gösterdiği yüksek enerji ve bitiricilik yeteneğiyle, Komodor FC'nin hücum gücüne önemli katkılarda bulunuyor ve kritik anlarda takımının güvenilir gol silahı olarak öne çıkıyor.",
  },
  {
    id: 18,
    firstName: "Zaim Aytunç",
    lastName: "Çakır",
    position: "Forvet",
    birthdate: 1998,
    shirtNum: 7,
    game: 4,
    goal: 3,
    assist: 2,
    redCard: 1,
    yellowCard: 1,
    photo: aytuncImg,
    insta: "https://www.instagram.com/cakiraytuncc",
    desc: "Takımın asıl golcüsü olan Aytunç, inanılmaz top tekniği ve mükemmel bitiriciliğiyle tanınıyor. Rakip savunmaları aşma konusunda gösterdiği ustalık ve her pozisyondan gol atma yeteneği, Komodor FC'nin hücum hattının en büyük güvencesi. Aytunç'un oyun zekası ve son vuruşlardaki başarısı, takımın gol yollarındaki en etkili silahı olmasını sağlıyor.",
  },
  {
    id: 19,
    firstName: "Taci Emre",
    lastName: "Şen",
    position: "Forvet",
    birthdate: 2002,
    shirtNum: 12,
    game: 1,
    goal: 0,
    assist: 0,
    redCard: 0,
    yellowCard: 0,
    photo: emreImg,
    insta: "https://www.instagram.com/_eemreee",
    desc: "Takımın bir diğer golcüsü olan Emre, nispeten az süre bulmasına rağmen sahaya girdiğinde maçın kaderini değiştirme yeteneğine sahip. Kısıtlı sürelerde bile yüksek performans sergileyerek, Komodor FC'nin hücumuna önemli katkılarda bulunuyor ve kritik anlarda etkili gol vuruşlarıyla maçları yönlendirebiliyor.",
  },
];
